[package]
name = "fe2o3"
version = "0.9.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/NitrogenLinux/elements"
license = "LICENSE"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.24.1"
tempfile = "3.3.0"
words-count = "0.1.3"
